### ISSUE TITLE
HDFS executor dies but datanode still running

### ISSUE THREAD

**Issue by abhay-agarwal** [mesosphere/hdfs#104]
Executor dies with a TASK_LOST:
```
22:19:40.065 [Thread-843] INFO  org.apache.mesos.hdfs.Scheduler - Received status update for taskId=task.datanode.datanode.NodeExecutor.1426888683532 state=TASK_LOST message='Abnormal executor termination' stagingTasks.size=0
22:19:40.074 [Thread-844] INFO  org.apache.mesos.hdfs.Scheduler - Received status update for taskId=task.datanode.datanode.NodeExecutor.1426888683532 state=TASK_LOST message='Abnormal executor termination' stagingTasks.size=0
22:19:40.076 [Thread-845] INFO  org.apache.mesos.hdfs.Scheduler - Received status update for taskId=task.datanode.datanode.NodeExecutor.1426888683532 state=TASK_LOST message='Abnormal executor termination' stagingTasks.size=0
22:19:40.079 [Thread-846] INFO  org.apache.mesos.hdfs.Scheduler - Received status update for taskId=task.datanode.datanode.NodeExecutor.1426888683532 state=TASK_LOST message='Abnormal executor termination' stagingTasks.size=0
22:19:41.016 [Thread-847] INFO  org.apache.mesos.hdfs.Scheduler - Received 1 offers
22:19:43.019 [Thread-848] INFO  org.apache.mesos.hdfs.Scheduler - Received 2 offers
22:19:44.020 [Thread-849] INFO  org.apache.mesos.hdfs.Scheduler - Received 2 offers
22:19:44.021 [Thread-849] INFO  org.apache.mesos.hdfs.Scheduler - Launching node of type datanode with tasks [datanode]
22:19:46.022 [Thread-850] INFO  org.apache.mesos.hdfs.Scheduler - Received 1 offers
22:19:46.024 [Thread-850] INFO  org.apache.mesos.hdfs.Scheduler - Already running hdfs task on slave6.test-suite.msphere.co
22:19:46.782 [Thread-851] INFO  org.apache.mesos.hdfs.Scheduler - Received status update for taskId=task.datanode.datanode.NodeExecutor.1426889984021 state=TASK_RUNNING message='' stagingTasks.size=1
22:19:46.782 [Thread-851] INFO  org.apache.mesos.hdfs.Scheduler - Current Acquisition Phase: DATA_NODES
```

But the actual process keeps restarting:
```
15/03/20 21:58:23 INFO common.Storage: Lock on /tmp/hdfs/data/data/in_use.lock acquired by nodename 22653@ip-10-171-113-184.ec2.internal
15/03/20 21:58:23 WARN common.Storage: java.io.IOException: Incompatible clusterIDs in /tmp/hdfs/data/data: namenode clusterID = CID-970065b9-6ce5-4429-93ea-c3848cea115d; datanode clusterID = CID-5bec4180-e25d-4bcf-8c94-48c697b88ad0
15/03/20 21:58:23 INFO common.Storage: Lock on /tmp/hdfs/data/data/in_use.lock acquired by nodename 22653@ip-10-171-113-184.ec2.internal
15/03/20 21:58:23 WARN common.Storage: java.io.IOException: Incompatible clusterIDs in /tmp/hdfs/data/data: namenode clusterID = CID-970065b9-6ce5-4429-93ea-c3848cea115d; datanode clusterID = CID-5bec4180-e25d-4bcf-8c94-48c697b88ad0
15/03/20 21:58:23 FATAL datanode.DataNode: Initialization failed for Block pool <registering> (Datanode Uuid unassigned) service to namenode1.hdfs.mesos/10.154.8.101:50071. Exiting. 
java.io.IOException: All specified directories are failed to load.
	at org.apache.hadoop.hdfs.server.datanode.DataStorage.recoverTransitionRead(DataStorage.java:463)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.initStorage(DataNode.java:1318)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.initBlockPool(DataNode.java:1288)
	at org.apache.hadoop.hdfs.server.datanode.BPOfferService.verifyAndSetNamespaceInfo(BPOfferService.java:320)
	at org.apache.hadoop.hdfs.server.datanode.BPServiceActor.connectToNNAndHandshake(BPServiceActor.java:221)
	at org.apache.hadoop.hdfs.server.datanode.BPServiceActor.run(BPServiceActor.java:829)
	at java.lang.Thread.run(Unknown Source)
15/03/20 21:58:23 FATAL datanode.DataNode: Initialization failed for Block pool <registering> (Datanode Uuid unassigned) service to namenode2.hdfs.mesos/10.169.71.165:50071. Exiting. 
java.io.IOException: All specified directories are failed to load.
	at org.apache.hadoop.hdfs.server.datanode.DataStorage.recoverTransitionRead(DataStorage.java:463)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.initStorage(DataNode.java:1318)
	at org.apache.hadoop.hdfs.server.datanode.DataNode.initBlockPool(DataNode.java:1288)
	at org.apache.hadoop.hdfs.server.datanode.BPOfferService.verifyAndSetNamespaceInfo(BPOfferService.java:320)
	at org.apache.hadoop.hdfs.server.datanode.BPServiceActor.connectToNNAndHandshake(BPServiceActor.java:221)
	at org.apache.hadoop.hdfs.server.datanode.BPServiceActor.run(BPServiceActor.java:829)
	at java.lang.Thread.run(Unknown Source)
15/03/20 21:58:23 WARN datanode.DataNode: Ending block pool service for: Block pool <registering> (Datanode Uuid unassigned) service to namenode1.hdfs.mesos/10.154.8.101:50071
15/03/20 21:58:23 WARN datanode.DataNode: Ending block pool service for: Block pool <registering> (Datanode Uuid unassigned) service to namenode2.hdfs.mesos/10.169.71.165:50071
15/03/20 21:58:23 INFO datanode.DataNode: Removed Block pool <registering> (Datanode Uuid unassigned)
15/03/20 21:58:25 WARN datanode.DataNode: Exiting Datanode
15/03/20 21:58:25 INFO util.ExitUtil: Exiting with status 0
15/03/20 21:58:25 INFO datanode.DataNode: SHUTDOWN_MSG: 
/************************************************************
SHUTDOWN_MSG: Shutting down DataNode at ip-10-171-113-184.ec2.internal/10.171.113.184
************************************************************/
15/03/20 21:58:26 INFO datanode.DataNode: STARTUP_MSG: 
/************************************************************
STARTUP_MSG: Starting DataNode
STARTUP_MSG:   host = ip-10-171-113-184.ec2.internal/10.171.113.184
STARTUP_MSG:   args = []
STARTUP_MSG:   version = 2.5.0-cdh5.3.1
```

**Comment by nicgrayson** [comment]
I think this has to do with the bash process supervision.

**Comment by elingg** [comment]
@nicgrayson, yes with better supervision and restarting the process in the Executor as opposed to the bash script will avoid this unpredictable behavior.

**Comment by elingg** [comment]
This is now working properly with the process supervision fix
